# nyxvamp: override variant (fully transparent)
# author: zoedsoupe <zoey.spessanha@zeetech.io>

inherits = "nyxvamp-veil"

# Override UI elements for transparency while maintaining readability
"ui.background" = {}
"ui.statusline" = { fg = "status_fg" }
"ui.statusline.inactive" = { fg = "status_inactive_fg" }
"ui.cursorline.primary" = {}
"ui.virtual.ruler" = {}

# Keep menus fully transparent but improve text contrast
"ui.menu" = { fg = "bright_text" }
"ui.menu.selected" = { fg = "selected_bright", bg = "selection_subtle", modifiers = ["bold"] }
"ui.menu.scroll" = { fg = "menu_scroll_fg" }

# Popups remain transparent with better text
"ui.popup" = { fg = "bright_text" }
"ui.popup.info" = { fg = "bright_text" }

# Improve picker visibility while keeping transparency
"ui.picker.header" = { fg = "header_bright", modifiers = ["bold", "underlined"] }
"ui.picker.header.column" = { fg = "header_bright" }
"ui.picker.header.column.active" = { fg = "selected_bright", modifiers = ["bold", "underlined"] }

# Focus and selection improvements
"ui.text.focus" = { fg = "selected_bright", bg = "selection_subtle", modifiers = ["bold"] }
"ui.text.inactive" = { fg = "text_inactive_fg" }
"ui.text.directory" = { fg = "directory_fg", modifiers = ["italic"] }

# Improve other UI elements
"ui.match_paren" = { fg = "match_paren_fg", bg = "match_paren_highlight_bg", modifiers = ["bold"] }
"ui.selection" = { bg = "selection_transparent" }
"ui.selection.primary" = { bg = "selection_primary_transparent" }

# Add palette for transparent-specific colors
[palette]
# Maximum contrast text colors for transparent backgrounds
bright_text = "#FFFFFF"  # Pure white text for maximum readability
selected_bright = "#FF69B4"  # Bright magenta pink for selections
header_bright = "#00BFFF"  # Bright sky blue for headers
directory_fg = "#00FF7F"  # Bright spring green for directories
text_inactive_fg = "#9CA3AF"  # Light gray for inactive text

# Stronger selection backgrounds for visibility
selection_subtle = "#F5C2E750"  # 31% transparent pink selection - much more visible
match_paren_highlight_bg = "#F28FAD40"  # 25% transparent pink highlight
selection_transparent = "#494D6450"  # 31% transparent selection
selection_primary_transparent = "#494D6460"  # 37.5% transparent primary selection
