# nyxvamp: override variant (fully transparent)
# author: zoedsoupe <zoey.spessanha@zeetech.io>

inherits = "nyxvamp-veil"

# Override UI elements for transparency while maintaining readability
"ui.background" = {}
"ui.statusline" = { fg = "status_fg" }
"ui.statusline.inactive" = { fg = "status_inactive_fg" }
"ui.cursorline.primary" = {}
"ui.virtual.ruler" = {}

# Keep menus fully transparent but improve text contrast
"ui.menu" = { fg = "bright_text" }
"ui.menu.selected" = { fg = "selected_bright", bg = "selection_subtle", modifiers = ["bold"] }
"ui.menu.scroll" = { fg = "menu_scroll_fg" }

# Popups remain transparent with better text
"ui.popup" = { fg = "bright_text" }
"ui.popup.info" = { fg = "bright_text" }

# Improve picker visibility while keeping transparency
"ui.picker.header" = { fg = "header_bright", modifiers = ["bold", "underlined"] }
"ui.picker.header.column" = { fg = "header_bright" }
"ui.picker.header.column.active" = { fg = "selected_bright", modifiers = ["bold", "underlined"] }

# Focus and selection improvements
"ui.text.focus" = { fg = "selected_bright", bg = "selection_subtle", modifiers = ["bold"] }
"ui.text.inactive" = { fg = "text_inactive_fg" }
"ui.text.directory" = { fg = "directory_fg", modifiers = ["italic"] }

# Improve other UI elements
"ui.match_paren" = { fg = "match_paren_fg", bg = "match_paren_highlight_bg", modifiers = ["bold"] }
"ui.selection" = { bg = "selection_transparent" }
"ui.selection.primary" = { bg = "selection_primary_transparent" }

# Add palette for transparent-specific colors
[palette]
# High-contrast text colors for transparent backgrounds
bright_text = "#D9E0EE"  # Bright white text
selected_bright = "#F28FAD"  # Bright pink for selections
header_bright = "#96CDFB"  # Bright blue for headers
directory_fg = "#ABE9B3"  # Green for directories
text_inactive_fg = "#6E6A86"  # Dimmed text

# Very subtle selection backgrounds (minimal opacity)
selection_subtle = "#F5C2E715"  # 8% transparent pink selection
match_paren_highlight_bg = "#F28FAD20"  # 12.5% transparent pink highlight
selection_transparent = "#494D6425"  # 15% transparent selection
selection_primary_transparent = "#494D6435"  # 20% transparent primary selection
