# nyxvamp: override variant (fully transparent)
# author: zoedsoupe <zoey.spessanha@zeetech.io>

inherits = "nyxvamp-veil"

# Override UI elements for transparency while maintaining readability
"ui.background" = {}
"ui.statusline" = { fg = "status_fg" }
"ui.statusline.inactive" = { fg = "status_inactive_fg" }
"ui.cursorline.primary" = {}
"ui.virtual.ruler" = {}

# Keep menus fully transparent but improve text contrast
"ui.menu" = { fg = "bright_text" }
"ui.menu.selected" = { fg = "selected_bright", bg = "selection_subtle", modifiers = ["bold"] }
"ui.menu.scroll" = { fg = "menu_scroll_fg" }

# Popups remain transparent with better text
"ui.popup" = { fg = "bright_text" }
"ui.popup.info" = { fg = "bright_text" }

# Improve picker visibility while keeping transparency
"ui.picker.header" = { fg = "header_bright", modifiers = ["bold", "underlined"] }
"ui.picker.header.column" = { fg = "header_bright" }
"ui.picker.header.column.active" = { fg = "selected_bright", modifiers = ["bold", "underlined"] }

# Focus and selection improvements
"ui.text.focus" = { fg = "selected_bright", bg = "selection_subtle", modifiers = ["bold"] }
"ui.text.inactive" = { fg = "text_inactive_fg" }
"ui.text.directory" = { fg = "directory_fg", modifiers = ["italic"] }

# Improve other UI elements
"ui.match_paren" = { fg = "match_paren_fg", bg = "match_paren_highlight_bg", modifiers = ["bold"] }
"ui.selection" = { bg = "selection_transparent" }
"ui.selection.primary" = { bg = "selection_primary_transparent" }

# Add palette for transparent-specific colors
[palette]
# Darker muted colors for transparent backgrounds - better contrast without being harsh
bright_text = "#E6E6FA"  # Slightly brighter lavender for readability
selected_bright = "#DDA0DD"  # Muted plum - darker than original pink but still visible
header_bright = "#87CEEB"  # Muted sky blue - darker than original
directory_fg = "#98D982"  # Muted sage green - darker than original
text_inactive_fg = "#696969"  # Darker gray for better hierarchy

# Stronger selection backgrounds for transparent theme
selection_subtle = "#DDA0DD50"  # 31% muted plum selection
match_paren_highlight_bg = "#DDA0DD40"  # 25% muted plum highlight
selection_transparent = "#483D8B40"  # 25% dark slate blue selection
selection_primary_transparent = "#483D8B50"  # 31% dark slate blue primary
